# Generated by Django 4.2.7 on 2023-11-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.IntegerField(default=0)),
                ('cpu_bursts', models.JSONField(default=list)),
                ('io_bursts', models.JSONField(default=list)),
                ('current_burst', models.IntegerField(blank=True, null=True)),
                ('current_burst_type', models.CharField(blank=True, max_length=255, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('time_spent_in_wait_queue', models.IntegerField(default=0)),
                ('time_spent_in_ready_queue', models.IntegerField(default=0)),
                ('time_spent_in_running_queue', models.IntegerField(default=0)),
                ('time_spent_in_IO_queue', models.IntegerField(default=0)),
                ('last_cycle_time', models.IntegerField(default=0)),
                ('response', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
