# Generated by Django 4.2.7 on 2023-11-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_model',
            name='message',
            field=models.CharField(blank=True, max_length=200000),
        ),
        migrations.AlterField(
            model_name='process_model',
            name='priority',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
