# Generated by Django 4.2.7 on 2023-11-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_process_model_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_model',
            name='process_in_ready_in_last_cycle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='process_model',
            name='total_time',
            field=models.IntegerField(default=0),
        ),
    ]
